In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# import plotly as plo
%matplotlib inline

In [2]:
df=pd.read_csv('survey_results_public.csv')

In [3]:
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1                     I am a developer by profession      Yes   
1           2                     I am a developer by profession       No   
2           3                        I code primarily as a hobby      Yes   
3           4                     I am a developer by profession      Yes   
4           5  I used to be a developer by profession, but no...      Yes   

    Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country  \
0   NaN         13  Monthly        NaN            NaN             Germany   
1   NaN         19      NaN        NaN            NaN      United Kingdom   
2   NaN         15      NaN        NaN            NaN  Russian Federation   
3  25.0         18      NaN        NaN            NaN             Albania   
4  31.0         16      NaN        NaN            NaN       United States   

     CurrencyDesc  ...                  SurveyEase           SurveyLength  \
0   European Euro  ...  Neither easy nor difficult  Appropriate in length   
1  Pound sterling  ...                         NaN                    NaN   
2             NaN  ...  Neither easy nor difficult  Appropriate in length   
3    Albanian lek  ...                         NaN                    NaN   
4             NaN  ...                        Easy              Too short   

  Trans                                     UndergradMajor  \
0    No  Computer science, computer engineering, or sof...   
1   NaN  Computer science, computer engineering, or sof...   
2   NaN                                                NaN   
3    No  Computer science, computer engineering, or sof...   
4    No  Computer science, computer engineering, or sof...   

  WebframeDesireNextYear    WebframeWorkedWith  \
0           ASP.NET Core  ASP.NET;ASP.NET Core   
1                    NaN                   NaN   
2                    NaN                   NaN   
3                    NaN                   NaN   
4   Django;Ruby on Rails         Ruby on Rails   

                              WelcomeChange WorkWeekHrs YearsCode YearsCodePro  
0   Just as welcome now as I felt last year        50.0        36           27  
1  Somewhat more welcome now than last year         NaN         7            4  
2  Somewhat more welcome now than last year         NaN         4          NaN  
3  Somewhat less welcome now than last year        40.0         7            4  
4   Just as welcome now as I felt last year         NaN        15            8  

[5 rows x 61 columns]

In [4]:
df = df[["Country", "EdLevel", "YearsCodePro", "Employment", "ConvertedComp"]]
df = df.rename({"ConvertedComp": "Salary"}, axis=1)
df.head()


Country                                          EdLevel  \
0             Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
1      United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2  Russian Federation                                              NaN   
3             Albania  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
4       United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

  YearsCodePro                                         Employment  Salary  
0           27  Independent contractor, freelancer, or self-em...     NaN  
1            4                                 Employed full-time     NaN  
2          NaN                                                NaN     NaN  
3            4                                                NaN     NaN  
4            8                                 Employed full-time     NaN

In [5]:
country_map=dict(df['Country'].value_counts())
country_map

{'United States': 12469,
 'India': 8403,
 'United Kingdom': 3896,
 'Germany': 3890,
 'Canada': 2191,
 'France': 1898,
 'Brazil': 1818,
 'Netherlands': 1343,
 'Poland': 1278,
 'Australia': 1208,
 'Spain': 1161,
 'Italy': 1117,
 'Russian Federation': 1092,
 'Sweden': 886,
 'Pakistan': 809,
 'Turkey': 777,
 'Israel': 653,
 'Switzerland': 629,
 'Bangladesh': 609,
 'Romania': 604,
 'Nigeria': 593,
 'Mexico': 540,
 'Austria': 539,
 'Ukraine': 539,
 'Czech Republic': 500,
 'Indonesia': 499,
 'South Africa': 494,
 'Iran': 491,
 'Belgium': 459,
 'Ireland': 444,
 'Philippines': 405,
 'Denmark': 397,
 'Argentina': 395,
 'Greece': 390,
 'Portugal': 388,
 'Norway': 384,
 'Hungary': 371,
 'China': 371,
 'Viet Nam': 364,
 'New Zealand': 353,
 'Finland': 349,
 'Bulgaria': 323,
 'Serbia': 306,
 'Japan': 297,
 'Sri Lanka': 295,
 'Colombia': 285,
 'Egypt': 281,
 'Kenya': 271,
 'Nepal': 242,
 'Malaysia': 231,
 'Singapore': 228,
 'South Korea': 201,
 'Slovakia': 188,
 'Croatia': 185,
 'Chile': 181,
 'Moroc

In [6]:
d={}

In [7]:
for t in country_map.keys():
    d[t]=(df[df['Country']==t]['Salary'].mean())

In [8]:
d

{'United States': 208826.49644259078,
 'India': 28751.27136431784,
 'United Kingdom': 140849.0741885626,
 'Germany': 92508.64733881436,
 'Canada': 115101.77546468402,
 'France': 74381.45874001774,
 'Brazil': 24941.354364736388,
 'Netherlands': 78552.95555555556,
 'Poland': 41857.167919799496,
 'Australia': 146165.81476683938,
 'Spain': 72619.35611038108,
 'Italy': 75963.87819548872,
 'Russian Federation': 36209.54854368932,
 'Sweden': 66937.70962199313,
 'Pakistan': 14581.384848484848,
 'Turkey': 26460.987012987014,
 'Israel': 111650.88554216867,
 'Switzerland': 142001.93628808865,
 'Bangladesh': 21586.559782608696,
 'Romania': 40103.11783439491,
 'Nigeria': 22399.287356321838,
 'Mexico': 29374.46815286624,
 'Austria': 83077.66134185303,
 'Ukraine': 35289.94314381271,
 'Czech Republic': 46250.961661341855,
 'Indonesia': 19266.477941176472,
 'South Africa': 54479.57525083612,
 'Iran': 21414.836363636365,
 'Belgium': 77264.65758754865,
 'Ireland': 183000.7403508772,
 'Philippines': 13737

In [9]:
df = df[df["Salary"].notnull()]
df.head()

Country                                            EdLevel  \
7    United States       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
9   United Kingdom    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
10  United Kingdom       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
11           Spain  Some college/university study without earning ...   
12     Netherlands  Secondary school (e.g. American high school, G...   

   YearsCodePro          Employment    Salary  
7            13  Employed full-time  116000.0  
9             4  Employed full-time   32315.0  
10            2  Employed full-time   40070.0  
11            7  Employed full-time   14268.0  
12           20  Employed full-time   38916.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34756 entries, 7 to 64154
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       34756 non-null  object 
 1   EdLevel       34188 non-null  object 
 2   YearsCodePro  34621 non-null  object 
 3   Employment    34717 non-null  object 
 4   Salary        34756 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.6+ MB


In [11]:
df=df[df['Employment']=='Employed full-time']

In [12]:
df['EdLevel'].value_counts()

Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          15229
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        7655
Some college/university study without earning a degree                                 3364
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     1160
Other doctoral degree (Ph.D., Ed.D., etc.)                                             1032
Associate degree (A.A., A.S., etc.)                                                    1025
Professional degree (JD, MD, etc.)                                                      423
I never completed any formal education                                                  121
Primary/elementary school                                                               118
Name: EdLevel, dtype: int64

In [13]:
df=df.dropna()

In [14]:
def clean_Ed(x):
    if 'Bachelor’s degree' in x:
        return 'Bachelor’s degree'
    if 'Master’s degree' in x:
        return 'Master’s degree'
    if 'Professional degree' in x or 'Other doctoral' in x:
        return 'Post grad'
    return 'Less than a Bachelors'

In [15]:
df['EdLevel']=df['EdLevel'].apply(clean_Ed)
df

Country                EdLevel      YearsCodePro  \
7       United States      Bachelor’s degree                13   
9      United Kingdom        Master’s degree                 4   
10     United Kingdom      Bachelor’s degree                 2   
11              Spain  Less than a Bachelors                 7   
12        Netherlands  Less than a Bachelors                20   
...               ...                    ...               ...   
64135         Denmark      Bachelor’s degree                 4   
64148        Colombia      Bachelor’s degree                 5   
64152   United States  Less than a Bachelors                20   
64153           Chile      Bachelor’s degree                 3   
64154           Japan      Bachelor’s degree  Less than 1 year   

               Employment    Salary  
7      Employed full-time  116000.0  
9      Employed full-time   32315.0  
10     Employed full-time   40070.0  
11     Employed full-time   14268.0  
12     Employed full-time   38916.0  
...                   ...       ...  
64135  Employed full-time   38208.0  
64148  Employed full-time   19428.0  
64152  Employed full-time     200.0  
64153  Employed full-time   15048.0  
64154  Employed full-time   38759.0  

[30019 rows x 5 columns]

In [16]:
def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'Other'
    return categorical_map

In [17]:
country_map = shorten_categories(df.Country.value_counts(), 400)
df['Country'] = df['Country'].map(country_map)
df.Country.value_counts()


Other                 8549
United States         7569
India                 2425
United Kingdom        2287
Germany               1903
Canada                1178
Brazil                 991
France                 972
Spain                  670
Australia              659
Netherlands            654
Poland                 566
Italy                  560
Russian Federation     522
Sweden                 514
Name: Country, dtype: int64

In [18]:
df

Country                EdLevel      YearsCodePro  \
7       United States      Bachelor’s degree                13   
9      United Kingdom        Master’s degree                 4   
10     United Kingdom      Bachelor’s degree                 2   
11              Spain  Less than a Bachelors                 7   
12        Netherlands  Less than a Bachelors                20   
...               ...                    ...               ...   
64135           Other      Bachelor’s degree                 4   
64148           Other      Bachelor’s degree                 5   
64152   United States  Less than a Bachelors                20   
64153           Other      Bachelor’s degree                 3   
64154           Other      Bachelor’s degree  Less than 1 year   

               Employment    Salary  
7      Employed full-time  116000.0  
9      Employed full-time   32315.0  
10     Employed full-time   40070.0  
11     Employed full-time   14268.0  
12     Employed full-time   38916.0  
...                   ...       ...  
64135  Employed full-time   38208.0  
64148  Employed full-time   19428.0  
64152  Employed full-time     200.0  
64153  Employed full-time   15048.0  
64154  Employed full-time   38759.0  

[30019 rows x 5 columns]

In [19]:
df['YearsCodePro'].unique()

array(['13', '4', '2', '7', '20', '1', '3', '12', '10', '14', '29', '6',
       '28', '8', '23', '15', '25', 'Less than 1 year', '5', '9', '11',
       '21', '16', '18', '32', '19', '22', '38', '30', '26', '17', '27',
       '24', '33', '34', '35', '36', '40', '39', 'More than 50 years',
       '31', '37', '41', '45', '42', '44', '43', '50', '49', '47', '46'],
      dtype=object)

In [20]:
def clean_exp(x):
    if x=='Less than 1 year':
        return 0.5
    if x=='More than 50 years':
        return 50
    return x

In [21]:
df['YearsCodePro'] = df['YearsCodePro'].apply(clean_exp)

In [22]:
df=df[df['Salary']<=250000]
df=df[df['Salary']>=10000]


In [23]:
df

Country                EdLevel YearsCodePro          Employment  \
7       United States      Bachelor’s degree           13  Employed full-time   
9      United Kingdom        Master’s degree            4  Employed full-time   
10     United Kingdom      Bachelor’s degree            2  Employed full-time   
11              Spain  Less than a Bachelors            7  Employed full-time   
12        Netherlands  Less than a Bachelors           20  Employed full-time   
...               ...                    ...          ...                 ...   
64129   United States        Master’s degree            4  Employed full-time   
64135           Other      Bachelor’s degree            4  Employed full-time   
64148           Other      Bachelor’s degree            5  Employed full-time   
64153           Other      Bachelor’s degree            3  Employed full-time   
64154           Other      Bachelor’s degree          0.5  Employed full-time   

         Salary  
7      116000.0  
9       32315.0  
10      40070.0  
11      14268.0  
12      38916.0  
...         ...  
64129  150000.0  
64135   38208.0  
64148   19428.0  
64153   15048.0  
64154   38759.0  

[25374 rows x 5 columns]

In [24]:
df.drop(['Employment'],axis=1,inplace=True)
df

Country                EdLevel YearsCodePro    Salary
7       United States      Bachelor’s degree           13  116000.0
9      United Kingdom        Master’s degree            4   32315.0
10     United Kingdom      Bachelor’s degree            2   40070.0
11              Spain  Less than a Bachelors            7   14268.0
12        Netherlands  Less than a Bachelors           20   38916.0
...               ...                    ...          ...       ...
64129   United States        Master’s degree            4  150000.0
64135           Other      Bachelor’s degree            4   38208.0
64148           Other      Bachelor’s degree            5   19428.0
64153           Other      Bachelor’s degree            3   15048.0
64154           Other      Bachelor’s degree          0.5   38759.0

[25374 rows x 4 columns]

In [25]:
df

Country                EdLevel YearsCodePro    Salary
7       United States      Bachelor’s degree           13  116000.0
9      United Kingdom        Master’s degree            4   32315.0
10     United Kingdom      Bachelor’s degree            2   40070.0
11              Spain  Less than a Bachelors            7   14268.0
12        Netherlands  Less than a Bachelors           20   38916.0
...               ...                    ...          ...       ...
64129   United States        Master’s degree            4  150000.0
64135           Other      Bachelor’s degree            4   38208.0
64148           Other      Bachelor’s degree            5   19428.0
64153           Other      Bachelor’s degree            3   15048.0
64154           Other      Bachelor’s degree          0.5   38759.0

[25374 rows x 4 columns]

In [26]:
from sklearn.preprocessing import LabelEncoder
le_education = LabelEncoder()
df['EdLevel'] = le_education.fit_transform(df['EdLevel'])
df["EdLevel"].unique()

array([0, 2, 1, 3])

In [27]:
le_country = LabelEncoder()
df['Country'] = le_country.fit_transform(df['Country'])
df["Country"].unique()

array([14, 13, 11,  7,  4,  2,  8,  6,  1,  3,  5, 12,  9,  0, 10])

In [28]:
df

Country  EdLevel YearsCodePro    Salary
7           14        0           13  116000.0
9           13        2            4   32315.0
10          13        0            2   40070.0
11          11        1            7   14268.0
12           7        1           20   38916.0
...        ...      ...          ...       ...
64129       14        2            4  150000.0
64135        8        0            4   38208.0
64148        8        0            5   19428.0
64153        8        0            3   15048.0
64154        8        0          0.5   38759.0

[25374 rows x 4 columns]

In [29]:
X=df[['Country','EdLevel','YearsCodePro']]
y=df['Salary']

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [31]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)

LinearRegression()

In [32]:
predictions=linear_reg.predict(X_test)

In [33]:
from sklearn import metrics

print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

MAE: 30503.343975960237
MSE: 1534387253.0873218
RMSE: 39171.25544436024


In [34]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

error = np.sqrt(mean_squared_error(y_test, predictions))

In [35]:
error

39171.25544436024

In [36]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=10)
dec_tree_reg.fit(X_train, y_train)

DecisionTreeRegressor(random_state=10)

In [37]:
y_pred = dec_tree_reg.predict(X)

In [38]:
error = np.sqrt(mean_squared_error(y, y_pred))
print("${:,.02f}".format(error))

$30,514.75


In [39]:
from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0,n_estimators=100)
random_forest_reg.fit(X, y.values)
y_pred = random_forest_reg.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
print("${:,.02f}".format(error))

$29,929.44


In [40]:
r= np.array([["United States", 'Master’s degree', 15 ]])
r

array([['United States', 'Master’s degree', '15']], dtype='<U15')

In [41]:
r[:, 0] = le_country.transform(r[:,0])
r[:, 1] = le_education.transform(r[:,1])
r = r.astype(float)
r

array([[14.,  2., 15.]])

In [42]:
y_pred

array([128671.13133313,  68347.91220735,  44897.38302321, ...,
        38031.30698755,  34319.63923166,  31989.72826991])

In [43]:
r_pred = random_forest_reg.predict(r)

C:\Users\shahn\python\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


In [44]:
r_pred

array([146837.64546367])

In [45]:
import pickle

In [46]:
data = {"model": random_forest_reg, "le_country": le_country, "le_education": le_education}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [47]:
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
le_country = data["le_country"]
le_education = data["le_education"]

In [48]:
ae = regressor_loaded.predict(r)
ae

C:\Users\shahn\python\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([146837.64546367])